apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-java-app
  namespace: simple-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-java
  template:
    metadata:
      labels:
        app: simple-java
    spec:
      containers:
      - name: app
        image: venkateshdeshpande/simple-java-app:v1.1
        ports:
        - containerPort: 8080

