apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-java-app
  namespace: simple-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-java
  template:
    metadata:
      labels:
        app: simple-java
    spec:
      containers:
      - name: app
        image: venkateshdeshpande/simple-java-app:v1.1
        ports:
        - containerPort: 8080
                resources:
          requests:
            cpu: "100m"        # 0.1 CPU
            memory: "128Mi"    # 128 MiB RAM
          limits:
            cpu: "500m"        # 0.5 CPU
            memory: "512Mi"    # 512 MiB RAM
